version: '3.9'

services:
    news_app:
        container_name: news_app
        image: news-app-dev:1.0.0
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        working_dir: /usr/src/app
        ports:
            - 4000:4000
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
        command: >
            bash -c "
                yarn
                yarn dev --port 4000 --host
            "
        networks:
            - news-network

networks:
    news-network:
        driver: bridge
